### ISSUE TITLE
Weighting for guessWord

### ISSUE THREAD

**Issue by schwartzadev** [losc3571/Schottland_CSCI2275_FinalProject#6]
Per the readme, words that have been dequeued should have a higher likelihood of being guessed:

```
When you select the dequeue words to train algorithm option, all the words in the queue are
dequeued and the weights in the tree are updated based on words you used. In this way the
tree can learn words and then be more likely to guess them next time you enter the beginning of them.
```

I'm not sure, though, if the weights are actually a parameter for the tree algorithm. (See `AlphabetGraph::guessWord`)

I could totally be wrong about this, though...the weight just isn't jumping out at me 😉

**Comment by losc3571** [comment]
Hey I just want to clarify how this is supposed to behave a little. I believe it does work this way but if it doesn't seem to let me know. When you use the addWord method when dequeuing words, it should update the wieghts in the tree by adding branches and adding to their weights based off the words in the queue.  Then when the guessWord is used in the future, it should see the weights that where added by addWord earlier and be more likely to follow those paths because guessWord always traverses down the path with the highest weights.

**Comment by schwartzadev** [comment]
Aha! Gotcha! Thanks for the detail. Is that what's happening on `AlphabetGraph.cpp::139-148` (below)?

```cpp
        int biggestI = 0;
        int biggest = 0;
        for (int i = 0; i < temp->adj.size(); i++)
        {
            if (temp->adj[i].weight > biggestI)
            {
                biggest = i;
                biggestI = temp->adj[i].weight;
            }
        }
```

**Comment by losc3571** [comment]
Yes that's exactly what is happening there. I should clarify in the comments that I am staying on the highest weighted path. Sorry for the confusion!

**Comment by schwartzadev** [comment]
Cool, thanks again!
